name: 3 environments test workflow

on:
  workflow_dispatch:

jobs:
  dev-job:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v2

      - id: print pre-GITHUB_ENV
        name: Print pre GITHUB_ENV value
        run: echo $GITHUB_ENV
      
      - id: set-env
        name: Set environment variable
        run: echo "ENV_NAME=dev" >> $GITHUB_ENV

      - id: print post-GITHUB_ENV
        name: Print post GITHUB_ENV value
        run: echo $GITHUB_ENV

      - id: dev-stage
        name: Run a script in dev env
        run: |
          echo "Running in ${{ env.ENV_NAME }} environment"
  
