name: 3 environments test workflow

on:
  workflow_dispatch:

jobs:
  dev-job:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v2
      - id: dev-stage
        name: Run a script in dev env
        run: |
          echo "Running in <${{environment}}> environment"
  
