name: 3 environments test workflow

on:
  workflow_dispatch:

jobs:
  dev-job:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v2

      - id: print_pre
        name: Print pre GITHUB ENV value
        run: echo $GITHUB_ENV
      
      - id: set-env
        name: Set environment variable
        run: echo "ENV_NAMEd=dev" >> $GITHUB_ENV

      - id: print_post
        name: Print post GITHUB ENV value
        run: echo $GITHUB_ENV

      - id: dev-stage
        name: Run a script in QA env
        run: |
          echo "Running in ${{ env.ENV_NAMEd }} environment"

  QA-job:
    runs-on: ubuntu-latest
    # needs: dev-job
    environment: QA
    steps:
      - uses: actions/checkout@v2

      - id: print_pre
        name: Print pre GITHUB ENV value
        run: echo $GITHUB_ENV
      
      - id: set-env
        name: Set environment variable
        run: echo "ENV_NAMEq=qa" >> $GITHUB_ENV

      - id: print_post
        name: Print post GITHUB ENV value
        run: echo $GITHUB_ENV

      - id: dev-stage
        name: Run a script in dev env
        run: |
          echo "Running in ${{ env.ENV_NAMEq }} environment"
  
  # Prod-job:
  #   runs-on: ubuntu-latest
  #   needs: QA-job
  #   environment: Prod
  #   steps:
  #     - uses: actions/checkout@v2

  #     - id: print_pre
  #       name: Print pre GITHUB ENV value
  #       run: echo $GITHUB_ENV
      
  #     - id: set-env
  #       name: Set environment variable
  #       run: echo "ENV_NAMEp=prod" >> $GITHUB_ENV

  #     - id: print_post
  #       name: Print post GITHUB ENV value
  #       run: echo $GITHUB_ENV

  #     - id: dev-stage
  #       name: Run a script in Prod env
  #       run: |
  #         echo "Running in ${{ env.ENV_NAMEp }} environment"
  
