# stores an env var in job1 and retrieves the value in another job named job2
name: envVars Workflow

#on: push
on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variable
        run: |
          echo "envVar=123" >> $GITHUB_ENV # GITHUB_ENV is an env var that that contains a file path and "envVar=123" is written into that file
          echo $GITHUB_ENV # prints both the file path and envVar=123
          
      - name: Print environment variable
        run: echo $envVar # prints the value of environment variable envVar which is 123
        
      - name: Save environment variable to file
        run: |
          echo "envVar=123" > env_file.txt # writes "evnVar=123" into another file env_file.txt
          cat env_file.txt # prints envVar=123
          
      - name: Upload environment file
        uses: actions/upload-artifact@v2
        with:
          name: env-vars
          path: env_file.txt
      

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Download environment file
        uses: actions/download-artifact@v2
        with:
          name: env-vars
  
      - name: Set environment variables from file
        run: cat env_file.txt

      - name: Print environment variables from file
        run: |
              source env_file.txt
              echo $envVar
