   name: env vars
   on: push
   jobs:
      job1:
        runs-on: ubuntu-latest
        steps:
          - run: echo "MY_VAR=myvalue" >> env.txt
          - uses: actions/upload-artifact@v3
            with:
              name: env-file
              path: env.txt
    
      job2:
        runs-on: ubuntu-latest
        needs: job1
        steps:
          - uses: actions/download-artifact@v3
            with:
              name: env-file
          - run: source env.txt  # Sets MY_VAR in the environment
          - run: echo $MY_VAR  # Outputs "myvalue"
