# workflow to test workflow trigger after pr creation and approve/merge
name: PR Test Workflow

on:
  workflow_dispatch:
 # pull_request:
 #   types:
 #     - opened
 #     - synchronize
 #     - reopened
 #     - edited
 #   branches:
 #     - b1

jobs:
  dev-job:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v2

      - id: print_pre
        name: Print pre GITHUB ENV value
        run: echo $GITHUB_ENV
      
      - id: set-env
        name: Set environment variable
        run: echo "ENV_NAMEd=dev" >> $GITHUB_ENV

      - id: print_post
        name: Print post GITHUB ENV value
        run: echo $GITHUB_ENV

      - id: dev-stage
        name: Run a script in QA env
        run: |
          echo "Running in ${{ env.ENV_NAMEd }} environment"
  # job1:
  #   name: Job1
  #   runs-on: ubuntu-latest
  #   # permissions:
  #   #   contents: 'read'
  #   #   id-token: 'write'
  #   #   issues: 'write'
  #   #   pull-requests: 'write'

  #   # defaults:
  #   #   run:
  #   #     shell: bash

  #   steps:
  #   - id: init-plan
  #     name: Init-Plan
  #     run: echo ">>> This is the init and plan step"

  #   - id: apply
  #     if: github.event.pull_request.base.ref == 'b1' && github.event.pull_request.state == 'closed' && github.event.pull_request.merged == true
  #     name: Apply
  #     run: echo ">>> This is the apply step"
