name: Terraform Folder Test

on:
  pull_request:
    branches:
      - staging
    types:
      - opened
      - synchronize
      - closed
  push:
    paths:
      - 'terraform/**'

jobs:
  terraform_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Terraform Test
      run: |
        cd terraform
        cat "tf-file"
