name: Terraform Folder Test

on:
  # workflow_dispatch:
  pull_request:
    branches:
      - staging
      # - main
    types:
      - opened
      - synchronize
      - closed
  push:
    paths:
      - 'terraform/**'

jobs:
  terraform_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Log Event Details
      run: |
        echo "Event Name: ${{ github.event_name }}"
        echo "PR Num: ${{ github.event.pull_request.number }}"
        echo "Event Ref: ${{ github.event_ref }}"
        echo "PR ref: ${{ github.event.pull_request.head.ref }}"

    - name: Terraform Test
      run: |
        pwd
        cd terraform
        pwd
        cat "tf-file"
