name: Terraform Workflow

on:
  workflow_dispatch:
  # push:
  #   paths:
  #     - 'terraform/**'
  # pull_request:
  #   branches:
  #     - staging
  #     - main
  #   types:
  #     - opened
  #     - synchronize
  #     - closed

jobs:
  terraform_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Terraform Test
      run: |
        cd terraform
        cat "tf-file"
