name: Terraform Folder Test

on:
  # workflow_dispatch:
  push:
    paths:
      - 'terraform/**'
  pull_request:
    branches:
      - staging
      - main
    types:
      - opened
      - synchronize
      - closed

jobs:
  terraform_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Log Event Details
      run: |
        echo "Event Name: ${{ github.event.name }}"
        echo "Event Ref: ${{ github.event.ref }}"
        echo "Other relevant event properties..."

    - name: Terraform Test
      run: |
        cd terraform
        cat "tf-file"
